org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21
archives_base_name=wits
maven_group=com.telepathicgrunt

fabric_loader_version=0.15.11
fabric_api_version=0.102.0+1.21

neoforge_version=21.0.167
neoform_version=1.21-20240613.152323

# MC dependencies
jetbrains_annotations_version=26.0.1
asm_version=9.7
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28

## Mod Properties
mod_id=wits
mod_name=Wits
mod_version=1.3.1
mod_description=Use `\wits` command to get registry name of all structures where you are standing.
sources_url=https://github.com/TelepathicGrunt/WITS
issues_url=https://github.com/TelepathicGrunt/WITS/issues
license_url=https://github.com/TelepathicGrunt/WITS/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/909375

# Publishing
mod_group_id=telepathicgrunt.wits
curseforge_id=909375
modrinth_id=AVo2esap
