org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
minecraft_version=1.21.5
neoform_version=1.21.5-20250325.162830

# NeoForge
neoforge_version=21.5.2-beta

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.119.5+1.21.5

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7


## Mod Properties
mod_id=wits
mod_name=WITS
mod_version=1.4.1
mod_description=Use `\\wits` command to get registry name of all structures where you are standing.
sources_url=https://github.com/TelepathicGrunt/WITS
issues_url=https://github.com/TelepathicGrunt/WITS/issues
license_url=https://github.com/TelepathicGrunt/WITS/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/909375

# Publishing
mod_group_id=telepathicgrunt.wits
curseforge_id=909375
modrinth_id=AVo2esap