org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.1
archives_base_name=wits
maven_group=com.telepathicgrunt

fabric_loader_version=0.19.3
fabric_api_version=0.145.1+26.1

neoforge_version=26.1.0.19-beta
neoform_version=26.1-1

# MC dependencies
jetbrains_annotations_version=26.0.1
asm_version=9.7

## Mod Properties
mod_id=wits
mod_name=WITS
mod_version=1.4.3
mod_description=Use `\wits` command to get registry name of all structures where you are standing.
sources_url=https://github.com/TelepathicGrunt/WITS
issues_url=https://github.com/TelepathicGrunt/WITS/issues
license_url=https://github.com/TelepathicGrunt/WITS/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/909375

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id=909375
modrinth_id=AVo2esap
