modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="${issues_url}"
sourcesUrl="${sources_url}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_display_name}"
displayURL="${homepage_url}"
logoFile="wits_logo_wide.png"
logoBlur=false
authors="TelepathicGrunt"
description='''${mod_description}'''

[dependencies]
"${mod_id}" = [
    { modId = "neoforge", type = "required", versionRange = "*", ordering = "NONE" },
    { modId = "minecraft", type = "required", versionRange = "[26.1,)", ordering = "NONE" },
]
