modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/TelepathicGrunt/WITS/issues"
license="https://github.com/TelepathicGrunt/WITS/blob/latest-released/LICENSE"

[[mods]]
modId="wits"
logoFile= "wits_logo_wide.png"
logoBlur=false
version="${version}"
displayName="WITS"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wits"
authors="TelepathicGrunt"
description='''
Use `\\wits` command to get registry name of all structures where you are standing.
'''

[[dependencies.wits]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.3,)"